# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lee/Documents/C++/SnakeGL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lee/Documents/C++/SnakeGL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lee/Documents/C++/SnakeGL/CMakeFiles /home/lee/Documents/C++/SnakeGL//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lee/Documents/C++/SnakeGL/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named symlink_compile_commands

# Build rule for target.
symlink_compile_commands: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 symlink_compile_commands
.PHONY : symlink_compile_commands

# fast build rule for target.
symlink_compile_commands/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/symlink_compile_commands.dir/build.make CMakeFiles/symlink_compile_commands.dir/build
.PHONY : symlink_compile_commands/fast

src/Core/Core.o: src/Core/Core.cpp.o
.PHONY : src/Core/Core.o

# target to build an object file
src/Core/Core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Core/Core.cpp.o
.PHONY : src/Core/Core.cpp.o

src/Core/Core.i: src/Core/Core.cpp.i
.PHONY : src/Core/Core.i

# target to preprocess a source file
src/Core/Core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Core/Core.cpp.i
.PHONY : src/Core/Core.cpp.i

src/Core/Core.s: src/Core/Core.cpp.s
.PHONY : src/Core/Core.s

# target to generate assembly for a file
src/Core/Core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Core/Core.cpp.s
.PHONY : src/Core/Core.cpp.s

src/GUI/Coin.o: src/GUI/Coin.cpp.o
.PHONY : src/GUI/Coin.o

# target to build an object file
src/GUI/Coin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/GUI/Coin.cpp.o
.PHONY : src/GUI/Coin.cpp.o

src/GUI/Coin.i: src/GUI/Coin.cpp.i
.PHONY : src/GUI/Coin.i

# target to preprocess a source file
src/GUI/Coin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/GUI/Coin.cpp.i
.PHONY : src/GUI/Coin.cpp.i

src/GUI/Coin.s: src/GUI/Coin.cpp.s
.PHONY : src/GUI/Coin.s

# target to generate assembly for a file
src/GUI/Coin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/GUI/Coin.cpp.s
.PHONY : src/GUI/Coin.cpp.s

src/GUI/Map.o: src/GUI/Map.cpp.o
.PHONY : src/GUI/Map.o

# target to build an object file
src/GUI/Map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/GUI/Map.cpp.o
.PHONY : src/GUI/Map.cpp.o

src/GUI/Map.i: src/GUI/Map.cpp.i
.PHONY : src/GUI/Map.i

# target to preprocess a source file
src/GUI/Map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/GUI/Map.cpp.i
.PHONY : src/GUI/Map.cpp.i

src/GUI/Map.s: src/GUI/Map.cpp.s
.PHONY : src/GUI/Map.s

# target to generate assembly for a file
src/GUI/Map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/GUI/Map.cpp.s
.PHONY : src/GUI/Map.cpp.s

src/GUI/Snake.o: src/GUI/Snake.cpp.o
.PHONY : src/GUI/Snake.o

# target to build an object file
src/GUI/Snake.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/GUI/Snake.cpp.o
.PHONY : src/GUI/Snake.cpp.o

src/GUI/Snake.i: src/GUI/Snake.cpp.i
.PHONY : src/GUI/Snake.i

# target to preprocess a source file
src/GUI/Snake.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/GUI/Snake.cpp.i
.PHONY : src/GUI/Snake.cpp.i

src/GUI/Snake.s: src/GUI/Snake.cpp.s
.PHONY : src/GUI/Snake.s

# target to generate assembly for a file
src/GUI/Snake.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/GUI/Snake.cpp.s
.PHONY : src/GUI/Snake.cpp.s

src/GUI/Timer.o: src/GUI/Timer.cpp.o
.PHONY : src/GUI/Timer.o

# target to build an object file
src/GUI/Timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/GUI/Timer.cpp.o
.PHONY : src/GUI/Timer.cpp.o

src/GUI/Timer.i: src/GUI/Timer.cpp.i
.PHONY : src/GUI/Timer.i

# target to preprocess a source file
src/GUI/Timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/GUI/Timer.cpp.i
.PHONY : src/GUI/Timer.cpp.i

src/GUI/Timer.s: src/GUI/Timer.cpp.s
.PHONY : src/GUI/Timer.s

# target to generate assembly for a file
src/GUI/Timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/GUI/Timer.cpp.s
.PHONY : src/GUI/Timer.cpp.s

src/Game.o: src/Game.cpp.o
.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i
.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s
.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/Utils/Shader.o: src/Utils/Shader.cpp.o
.PHONY : src/Utils/Shader.o

# target to build an object file
src/Utils/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Utils/Shader.cpp.o
.PHONY : src/Utils/Shader.cpp.o

src/Utils/Shader.i: src/Utils/Shader.cpp.i
.PHONY : src/Utils/Shader.i

# target to preprocess a source file
src/Utils/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Utils/Shader.cpp.i
.PHONY : src/Utils/Shader.cpp.i

src/Utils/Shader.s: src/Utils/Shader.cpp.s
.PHONY : src/Utils/Shader.s

# target to generate assembly for a file
src/Utils/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Utils/Shader.cpp.s
.PHONY : src/Utils/Shader.cpp.s

src/Utils/Texture2D.o: src/Utils/Texture2D.cpp.o
.PHONY : src/Utils/Texture2D.o

# target to build an object file
src/Utils/Texture2D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Utils/Texture2D.cpp.o
.PHONY : src/Utils/Texture2D.cpp.o

src/Utils/Texture2D.i: src/Utils/Texture2D.cpp.i
.PHONY : src/Utils/Texture2D.i

# target to preprocess a source file
src/Utils/Texture2D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Utils/Texture2D.cpp.i
.PHONY : src/Utils/Texture2D.cpp.i

src/Utils/Texture2D.s: src/Utils/Texture2D.cpp.s
.PHONY : src/Utils/Texture2D.s

# target to generate assembly for a file
src/Utils/Texture2D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Utils/Texture2D.cpp.s
.PHONY : src/Utils/Texture2D.cpp.s

src/Utils/glad.o: src/Utils/glad.c.o
.PHONY : src/Utils/glad.o

# target to build an object file
src/Utils/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Utils/glad.c.o
.PHONY : src/Utils/glad.c.o

src/Utils/glad.i: src/Utils/glad.c.i
.PHONY : src/Utils/glad.i

# target to preprocess a source file
src/Utils/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Utils/glad.c.i
.PHONY : src/Utils/glad.c.i

src/Utils/glad.s: src/Utils/glad.c.s
.PHONY : src/Utils/glad.s

# target to generate assembly for a file
src/Utils/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/Utils/glad.c.s
.PHONY : src/Utils/glad.c.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/renderLoop.o: src/renderLoop.cpp.o
.PHONY : src/renderLoop.o

# target to build an object file
src/renderLoop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/renderLoop.cpp.o
.PHONY : src/renderLoop.cpp.o

src/renderLoop.i: src/renderLoop.cpp.i
.PHONY : src/renderLoop.i

# target to preprocess a source file
src/renderLoop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/renderLoop.cpp.i
.PHONY : src/renderLoop.cpp.i

src/renderLoop.s: src/renderLoop.cpp.s
.PHONY : src/renderLoop.s

# target to generate assembly for a file
src/renderLoop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/renderLoop.cpp.s
.PHONY : src/renderLoop.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... symlink_compile_commands"
	@echo "... test"
	@echo "... src/Core/Core.o"
	@echo "... src/Core/Core.i"
	@echo "... src/Core/Core.s"
	@echo "... src/GUI/Coin.o"
	@echo "... src/GUI/Coin.i"
	@echo "... src/GUI/Coin.s"
	@echo "... src/GUI/Map.o"
	@echo "... src/GUI/Map.i"
	@echo "... src/GUI/Map.s"
	@echo "... src/GUI/Snake.o"
	@echo "... src/GUI/Snake.i"
	@echo "... src/GUI/Snake.s"
	@echo "... src/GUI/Timer.o"
	@echo "... src/GUI/Timer.i"
	@echo "... src/GUI/Timer.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/Utils/Shader.o"
	@echo "... src/Utils/Shader.i"
	@echo "... src/Utils/Shader.s"
	@echo "... src/Utils/Texture2D.o"
	@echo "... src/Utils/Texture2D.i"
	@echo "... src/Utils/Texture2D.s"
	@echo "... src/Utils/glad.o"
	@echo "... src/Utils/glad.i"
	@echo "... src/Utils/glad.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/renderLoop.o"
	@echo "... src/renderLoop.i"
	@echo "... src/renderLoop.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

